application: mapitapps
version: 1
runtime: python27
threadsafe: yes
api_version: 1

handlers:
  
- url: /static
  static_dir: static
  expiration: 7d

- url: /.*
  script: app.app

builtins:
- remote_api: on

inbound_services:
- warmup


